sudo: required
services:
 - docker

before_install:
 - docker build -t pavelnn/docker-react -f Dockerfile.dev .

script:
 - docker run pavelnn/docker-react npm run test -- --coverage

deploy:
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "docker"
 env: "Docker-env"
 bucket_name: "elasticbeanstalk-us-east-2-908575468993"
 bucket_path: "docker"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access-key:
  secure: "$AWS_SECRET_KEY"
